# Generated by Django 4.1.7 on 2023-04-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_facilitator'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='facilitator',
            field=models.CharField(default='Mr M.', max_length=200),
        ),
        migrations.DeleteModel(
            name='Facilitator',
        ),
    ]
